version: '3.8'

services:
  postgres-metadata:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-metadata-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5
    restart: always
    networks:
      - pipeline-network

  postgres-staging:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: staging_user
      POSTGRES_PASSWORD: staging_pass
      POSTGRES_DB: telecom_staging
    volumes:
      - postgres-staging-data:/var/lib/postgresql/data
      - ./sql/staging:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "staging_user"]
      interval: 10s
      retries: 5
    restart: always
    networks:
      - pipeline-network

  postgres-analytics:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: telecom_analytics
    volumes:
      - postgres-analytics-data:/var/lib/postgresql/data
      - ./sql/analytics:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "analytics_user"]
      interval: 10s
      retries: 5
    restart: always
    networks:
      - pipeline-network

  spark-master:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: spark-master

    entrypoint: []
    command: 
      - "/home/airflow/.local/lib/python3.11/site-packages/pyspark/bin/spark-class"
      - "org.apache.spark.deploy.master.Master"
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark:/opt/airflow/spark
      - ./data:/opt/spark/data
    networks:
      - pipeline-network
    restart: always

  spark-worker:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    container_name: spark-worker
    depends_on:
      - spark-master
    entrypoint: []
    command: 
      - "/home/airflow/.local/lib/python3.11/site-packages/pyspark/bin/spark-class"
      - "org.apache.spark.deploy.worker.Worker"
      - "spark://spark-master:7077"
    ports:
      - "8081:8081"
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
    volumes:
      - ./spark:/opt/airflow/spark
      - ./data:/opt/airflow/data
    networks:
      - pipeline-network
    restart: always

  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-metadata:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db init
        airflow users create \
          --username admin \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email prashantpathak4144@gmail.com \
          --password admin
    depends_on:
      postgres-metadata:
        condition: service_healthy
    networks:
      - pipeline-network

  airflow-webserver:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-metadata:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: webserver
    ports:
      - "8082:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - ./spark:/opt/airflow/spark
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - pipeline-network

  airflow-scheduler:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-metadata:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__WEBSERVER__SECRET_KEY: 'UKMzEm3yIuFYEq1y3-2FxPNWSVwRASpahmQ9kQfEr8E='
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
      - ./sql:/opt/airflow/sql
      - ./spark:/opt/airflow/spark
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - pipeline-network


networks:
  pipeline-network:
    driver: bridge

volumes:
  postgres-metadata-data:
  postgres-staging-data:
  postgres-analytics-data:
  